### PR TITLE
Properly treat caching headers

### PR DESCRIPTION
**Pull request by ShimShtein**

### CODE REVIEW

**Comment by ShimShtein** [comment]
@subpop, can give it a spin? This should fix e-tag mishgandling.

**Comment by ShimShtein** [comment]
Test failure is unrelated.

**Comment by subpop** [comment]
This looks like a reasonable fix. I don't have a Satellite install readily available to test it with though.

**Comment by Ichimonji10** [comment]
Fix verified. See: https://issues.redhat.com/browse/REMEDY-43

**Comment by ShimShtein** [comment]
@Ron-Lavi Want to press the button?

**Review by Ron-Lavi — APPROVED** [review]
Looks safe to me 👍🏼

**Comment by Ron-Lavi** [comment]
Thanks @ShimShtein @subpop @Ichimonji10 !!

**Pull request merged**
