### PR TITLE
[CP_24] Add InventoryFilter

### PR DESCRIPTION
**Pull request by laviro**

### CODE REVIEW

**Comment by ShimShtein** [comment]
Minor bug I have found:
image
I think we need a separate PR in master for that. Notice the filter isn't cleared when moving to "Any organization". It's only the text that does not change.

**Comment by laviro** [comment]
Thanks @ShimShtein, I created a fix for that on master first: see #210
when it's merged I will add it in this PR

**Comment by laviro** [comment]
added the fix as the last commit, ready for another round @ShimShtein

**Comment by ShimShtein** [comment]
Now we need to cherry pick it into 20

**Pull request merged**
