### PR TITLE
Add ping status server side

### PR DESCRIPTION
**Pull request by ShimShtein**

### CODE REVIEW

**Comment by ShimShtein** [comment]
@laviro, found the bug with cert endpoint and fixed it

**Comment by ShimShtein** [comment]
@lphiri, your review would be much appreciated

**Review by laviro — APPROVED** [review]
Works great @ShimShtein !
tested with the frontend side in #622

**Review by lphiri — APPROVED** [review]
LGTM!

**Comment by laviro** [comment]
Thanks @ShimShtein ! tested again and it works :)

**Pull request merged**
