### PR TITLE
Convert all reported tag values to string

### PR DESCRIPTION
**Pull request by ShimShtein**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Isn't this a bit non-standard json dumping behavior?

**Comment by ShimShtein** [comment]
Are you referring to the `@stream` pattern? Yes, it's not standard, the problem is there is no standard json streaming library, and I didn't want to keep all the report object in memory, it's just too big.

**Comment by adamruzicka** [comment]
I commented before knowing what's going on, I wasn't aware that the thing processing the uploaded data requires all values to be strings. Feel free to ignore the previous comment

**Review by laviro — APPROVED** [review]
Thanks @ShimShtein !

**Pull request merged**
