### PR TITLE
Fix design issues on page header and settings

### PR DESCRIPTION
**Pull request by laviro**
Before:
Screenshot - 2021-07-26T123624 879

After:
Screenshot - 2021-07-26T180131 028

### CODE REVIEW

**Comment by laviro** [comment]
@ShimShtein added also pagination to the buttons toolbar
Screenshot - 2021-07-26T114721 606

**Comment by laviro** [comment]
Applied also for the searchbar:
Screenshot - 2021-07-26T134340 091

**Comment by laviro** [comment]
@ShimShtein ready for review :)

**Comment by MariSvirik** [comment]
Hey, @laviro  @ShimShtein this is my proposal. I used our index page template with padding and pink description text. What do you say?
Screenshot 2021-07-27 at 12 29 43

**Comment by laviro** [comment]
Thanks @MariSvirik for your detailed mockup,
I added most of the design-related issues, and since this PR is getting quite big, in follow-up PR I will handle:
- move the main checkbox to the toolbar
- make remediation cell a link
- add total-risk filter

This is how it looks now:
Screenshot - 2021-07-27T161412 236

**Comment by MariSvirik** [comment]
@laviro just fix 'Total Risk' column header to 'Total risk'. After I spent months on capitalization research for c.rh.c, I'm kind of a capitalization patrol.

**Comment by laviro** [comment]
Done @MariSvirik :)
@shimshtein ready for a final round!

**Comment by laviro** [comment]
Just did a big rebase after #538 got in

**Comment by ShimShtein** [comment]
Although we can do it in a follow up, I think it's quite important. In smaller windows, the "remediate" button disappears:

image

**Comment by ShimShtein** [comment]
@laviro, another thing that I am missing here is the change to "has_ansible" column to ansible/manual

**Comment by MariSvirik** [comment]
@ShimShtein if the window is too small either shorten a search input or add a kebab with an action 'Remediate' or do both. Depends on a size.

**Comment by MariSvirik** [comment]
> another thing that I am missing here is the change to "has_ansible" column to ansible/manual

The column name should be: Remediate
Values should be: (ansible icon) Playbook / Manual

**Comment by laviro** [comment]
> > another thing that I am missing here is the change to "has_ansible" column to ansible/manual
> 
> The column name should be: Remediate
> Values should be: (ansible icon) Playbook / Manual

Added it in the last commit:
Screenshot - 2021-08-01T134831 876

> Although we can do it in a follow up, I think it's quite important. In smaller windows, the "remediate" button disappears:

Fixed the responsiveness as much as I could:

https://user-images.githubusercontent.com/26363699/127768206-60f2fe48-7ac8-4aa4-816d-1833d63dac83.mp4

**Comment by ShimShtein** [comment]
Merged, thanks @laviro!

**Pull request merged**
