### PR TITLE
Inventory upload setting redesign to pf4

### PR DESCRIPTION
**Pull request by MariaAga**
Depends on https://github.com/theforeman/foreman_rh_cloud/pull/428
Starting the redesign of  the settings. Next I will need to add "red hat inventory" and "cloud connected"  settings and move the other settings to a modal.
Screenshot from 2020-12-27 12-39-18

### CODE REVIEW

**Comment by ShimShtein** [comment]
@MariaAga, can you rebase please?

**Comment by MariaAga** [comment]
Rebased, if you have some suggestions on the design I would love to hear them :smile:

**Review by ShimShtein — CHANGES_REQUESTED** [review]
image
Can we make them not so close to each other?

Also the main "card view" is a bit smaller than the screen. Can we get it back to the same width?

**Comment by MariaAga** [comment]
I removed the grid as it's not necessary any more and it added the padding. About spacing the settings: I don't see them like this, can you check if you have this css rule applied? `.foreman-switcher{ margin-bottom: 5px; }`

**Comment by MariaAga** [comment]
I made the css rule more specific and added a classname to the page so we only change the plugins css

**Comment by ShimShtein** [comment]
Merged, thanks @MariaAga!

**Pull request merged**
