### PR TITLE
SAT-28994 - Fix About subscription watch link on RH Cloud Inventory page

### PR DESCRIPTION
**Pull request by lfu**
**To test**

1. Go to Configure > RH Cloud > Inventory Upload page
2. Click on "About subscription watch" link.

The link should redirect to the document of Getting Started with the Subscriptions Service.

### CODE REVIEW

**Comment by chris1984** [comment]
@ColeHiggins2 can you test this with packit? I can do a code review on it.

**Review by chris1984 — COMMENTED** [review]
Looks like we need to update the JS snapshot here:
```bash
webpack/ForemanInventoryUpload/Components/PageHeader/components/PageDescription/__tests__/__snapshots__/PageDescription.test.js.snap:      href="https://access.redhat.com/documentation/en-us/subscription_central/2020-04/html/getting_started_with_subscription_watch/assembly-about-subscriptionwatch
```

**Review by chris1984 — APPROVED** [review]
Looks and works fine to me, waiting on @ColeHiggins2 to test it

**Review by ColeHiggins2 — COMMENTED** [review]
@chris1984 Tested with packit. Looks good to me!

**Pull request merged**
