### PR TITLE
Replace deprecated toast actions

### PR DESCRIPTION
**Pull request by MariaAga**

### CODE REVIEW

**Review by Ron-Lavi — COMMENTED** [review]
Works well, @ShimShtein seems that we will need to create a new branch for foreman_3_1
and master will continue with develop as this deprecation is only part of Foreman's develop: https://github.com/theforeman/foreman/pull/8951/

**Review by ShimShtein — APPROVED** [review]
Let's wait with the commit until we branch rh_cloud for foreman 3.1

**Comment by tbrisker** [comment]
The updated actions are available in 3.1 as well - https://projects.theforeman.org/issues/33690.

**Comment by Ron-Lavi** [comment]
> The updated actions are available in 3.1 as well - https://projects.theforeman.org/issues/33690.

@tbrisker iiuc the deprecation warning was in 3.1: https://github.com/theforeman/foreman/pull/8840/files#diff-a3d6955563d1c4c77410a5e2bef87e33f4b04a0a53a7f88b2725a99785d6c8deR3 but later on develop branch it was removed.

**Comment by Ron-Lavi** [comment]
rebased now that tests were updated to 3.1,
let's see if the compilation passes

**Comment by Ron-Lavi** [comment]
Thanks @MariaAga @tbrisker @ShimShtein let's get this in.

**Pull request merged**
