### PR TITLE
i18n - pulling from tx

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
Looks like CI is messed up in this repository:
```
Foreman::PluginRequirementError: ERF72-3740 [Foreman::PluginRequirementError]: foreman_rh_cloud plugin requires Foreman >= 3.7 but current is 3.6.2
```

**Comment by chris1984** [comment]
@ekohl can you rebase on the latest commit, I switched the container to the foreman_39 one

**Comment by ekohl** [comment]
Thanks for fixing CI, rebased.

**Comment by chris1984** [comment]
Test failure is unrelated, have a card to fix it, merging so we can get translations in. Thanks @ekohl

**Review by chris1984 — APPROVED** [review]

**Pull request merged**
