### PR TITLE
Add better error handling with toasts

### PR DESCRIPTION
**Pull request by laviro**
Each commit changes a component with better error handling.

### CODE REVIEW

**Comment by laviro** [comment]
@ShimShtein I refactored 5 components with better error handling,
each commit is for another component.

**Review by ShimShtein — CHANGES_REQUESTED** [review]
One issue found. Otherwise, it works well

- [x] Sync inventory button remains spinning

**Comment by laviro** [comment]
> Sync inventory button remains spinning

Fixed that one, good catch:

Screenshot (17)

**Review by ShimShtein — APPROVED** [review]

**Comment by ShimShtein** [comment]
Merged, thanks @laviro!

**Pull request merged**
