### PR TITLE
Move inventory settings to advanced settings modal

### PR DESCRIPTION
**Pull request by MariaAga**
Cloud connector and Red Hat Inventory settings don't do anything
Screenshot from 2020-12-30 18-48-41
Screenshot from 2020-12-30 18-48-47

### CODE REVIEW

**Comment by ShimShtein** [comment]
Where would you put the logic about which buttons should be checked when the main switch is changed?

**Comment by MariaAga** [comment]
@ShimShtein Probably in the actions when the back-end will be ready.
I can make mock actions in another pr

**Comment by adamruzicka** [comment]
What is the plan here?

**Comment by laviro** [comment]
Can we close this one? @ShimShtein @MariaAga

**Comment by laviro** [comment]
Thanks all, let's close it for now and if it will become relevant again we could reopen this :)

**Pull request closed without merging**
