### PR TITLE
 Add ouiaId prop to all supported components in host details

### PR DESCRIPTION
**Pull request by lfu**
Per https://issues.redhat.com/browse/SAT-11706

Related to https://github.com/Katello/katello/pull/10249

### CODE REVIEW

**Comment by lfu** [comment]
cc @jeremylenz

**Comment by lfu** [comment]
Can someone review this PR? Thanks.

**Comment by ShimShtein** [comment]
It's on my todo list. Which versions should it land into?

**Comment by lfu** [comment]
I think it's 6.12. @jeremylenz Correct me if I'm wrong.

**Pull request merged**
