### PR TITLE
Skip nics with empty identifier

### PR DESCRIPTION
**Pull request by ShimShtein**

### CODE REVIEW

**Comment by ShimShtein** [comment]
@adamruzicka this one needs a review too

**Review by adamruzicka — APPROVED** [review]
Again, would be curious to hear how this happens, but in general +1

**Comment by ShimShtein** [comment]
@laviro, ready for review/merge

**Review by laviro — APPROVED** [review]

**Comment by laviro** [comment]
Thanks @ShimShtein !

**Pull request merged**
