### PR TITLE
Fix uninitialized constant ForemanRhCloud::VERSION

### PR DESCRIPTION
**Pull request by stejskalleos**
Workflows:
- insights client registration
- rh_cloud_inventory:report:generate task

### CODE REVIEW

**Comment by stejskalleos** [comment]
@ofedoren

**Comment by ofedoren** [comment]
Thanks, @stejskalleos, that could do it. We could also try to do it future-proof: since we already remove that constant from Zeitwerk loader, we can explicitly require it in the same initializer, so we don't need to require it in each file that potentially uses that constant.
In https://github.com/theforeman/foreman_rh_cloud/blob/develop/config/initializers/zeitwerk.rb:
```ruby
require 'foreman_rh_cloud/version'

Rails.autoloaders.main.ignore(
  ForemanRhCloud::Engine.root.join('lib/foreman_rh_cloud/version.rb')
)
```

**Review by chris1984 — COMMENTED** [review]
I like @ofedoren method so we don't have to include it in each file, @stejskalleos can you update the pr and we can test

**Comment by jeremylenz** [comment]
I've also been getting some problems in foreman_theme_satellite with `Rails.autoloaders.main.ignore` - apparently `main` doesn't exist sometimes?

**Comment by ofedoren** [comment]
> I've also been getting some problems in foreman_theme_satellite with `Rails.autoloaders.main.ignore` - apparently `main` doesn't exist sometimes?

AFAIU, `.main` comes with Zeitwerk. Before that I think it was `.autoloaders.each` for Rails' ones?

**Review by ofedoren — APPROVED** [review]
Thanks, @stejskalleos, seems to fix the issue

**Review by chris1984 — APPROVED** [review]
Thanks @stejskalleos

**Pull request merged**
