### PR TITLE
Stop settings DB queries

### PR DESCRIPTION
**Pull request by ShimShtein**

### CODE REVIEW

**Comment by ShimShtein** [comment]
@Ron-Lavi care to take a final look?

**Comment by Ron-Lavi** [comment]
@ShimShtein time to move to a newer branch? :D
it fixed the issue with foreman develop

**Comment by ShimShtein** [comment]
@adamruzicka would you mind to review this one?

**Review by adamruzicka — APPROVED** [review]
ACK

**Comment by adamruzicka** [comment]
Thank you @ShimShtein !

**Pull request merged**
